# Generated by Django 3.1.5 on 2021-01-26 10:29

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=20)),
                ('schoolAddress', models.CharField(max_length=255)),
                ('maxStudent', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentId', models.CharField(blank=True, default=app.models.Student.create_id, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('dob', models.DateField()),
                ('schoolId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schoolIds', to='app.school')),
            ],
        ),
    ]
